### PR TITLE
Run ./gen.sh on M1 macOS

### PR DESCRIPTION
**Pull request by glacials**
Here's the output from running `./gen.sh` on M1 macOS, note the four `undefined` lines at the bottom. Fixes sc-6311.
```
target: darwin/arm64
host config cmd: /opt/homebrew/bin/cpp-11
C front end 1/11: upstream/tree-sitter/lib/src/get_changed_ranges.c ... 55.612709ms
C front end 2/11: upstream/tree-sitter/lib/src/language.c ... 21.117542ms
C front end 3/11: upstream/tree-sitter/lib/src/lexer.c ... 24.385ms
C front end 4/11: upstream/tree-sitter/lib/src/lib.c ... 102.262083ms
C front end 5/11: upstream/tree-sitter/lib/src/node.c ... 16.961209ms
C front end 6/11: upstream/tree-sitter/lib/src/parser.c ... 51.627708ms
C front end 7/11: upstream/tree-sitter/lib/src/query.c ... 55.2095ms
C front end 8/11: upstream/tree-sitter/lib/src/stack.c ... 19.110541ms
C front end 9/11: upstream/tree-sitter/lib/src/subtree.c ... 38.957875ms
C front end 10/11: upstream/tree-sitter/lib/src/tree.c ... 15.772667ms
C front end 11/11: upstream/tree-sitter/lib/src/tree_cursor.c ... 18.024958ms
processing file scope declarations ... 32.178375ms
processing symbol table ... 651.041µs
processing struct/union types ... 88.833958ms
processing enum values ... 3.838583ms
processing #defines ... 1.990833ms
processing static local declarations ... 25.530375ms
Go back end 1/11: get_changed_ranges.c ... 22.661833ms
Go back end 2/11: language.c ... 5.451708ms
Go back end 3/11: lexer.c ... 21.394291ms
Go back end 4/11: lib.c ... go.go:1337:err: TRC upstream/tree-sitter/lib/src/clock.h:124:20: error: back-end: undefined: clock (go.go:3228:declaratorDefault)
go.go:1337:err: TRC upstream/tree-sitter/lib/src/clock.h:124:20: error: back-end: undefined: clock (go.go:3228:declaratorDefault)
go.go:1337:err: TRC upstream/tree-sitter/lib/src/query.c:329:9: error: back-end: undefined: iswspace (go.go:3228:declaratorDefault)
go.go:1337:err: TRC upstream/tree-sitter/lib/src/query.c:329:9: error: back-end: undefined: iswspace (go.go:3228:declaratorDefault)
go.go:1337:err: TRC upstream/tree-sitter/lib/src/query.c:344:10: error: back-end: undefined: iswalnum (go.go:3228:declaratorDefault)
go.go:1337:err: TRC upstream/tree-sitter/lib/src/query.c:344:10: error: back-end: undefined: iswalnum (go.go:3228:declaratorDefault)
go.go:1337:err: TRC upstream/tree-sitter/lib/src/query.c:351:5: error: back-end: undefined: iswalnum (go.go:3228:declaratorDefault)
go.go:1337:err: TRC upstream/tree-sitter/lib/src/query.c:351:5: error: back-end: undefined: iswalnum (go.go:3228:declaratorDefault)
172.09975ms
Go back end 5/11: node.c ... 3.182292ms
Go back end 6/11: parser.c ... 3.467458ms
Go back end 7/11: query.c ... 3.769625ms
Go back end 8/11: stack.c ... 3.759125ms
Go back end 9/11: subtree.c ... 3.593375ms
Go back end 10/11: tree.c ... 3.225125ms
Go back end 11/11: tree_cursor.c ... 3.089791ms
upstream/tree-sitter/lib/src/clock.h:124:20: back-end: undefined: clock
upstream/tree-sitter/lib/src/query.c:329:9: back-end: undefined: iswspace
upstream/tree-sitter/lib/src/query.c:344:10: back-end: undefined: iswalnum
upstream/tree-sitter/lib/src/query.c:351:5: back-end: undefined: iswalnum
```

### CODE REVIEW

**Review by zombiezen — CHANGES_REQUESTED** [review]
Yeah, these lines from gen.sh were what I was afraid of:

```
upstream/tree-sitter/lib/src/clock.h:124:20: back-end: undefined: clock
upstream/tree-sitter/lib/src/query.c:329:9: back-end: undefined: iswspace
upstream/tree-sitter/lib/src/query.c:344:10: back-end: undefined: iswalnum
upstream/tree-sitter/lib/src/query.c:351:5: back-end: undefined: iswalnum
```

The treesitter_darwin_arm64.go file is a minimal stub because the ccgo project doesn't have implementations for these functions on darwin/arm64. We had to go through a similar hoop for linux/amd64 and darwin/amd64. If it's just that set of functions, that might be an easy fix, but if there's more code involved, then it might get trickier.

**Comment by zombiezen** [comment]
I reached out to Jan and he's pushed a new release that might address those errors. I added a commit that should pick up the appropriate changes. Can you pull down the branch and re-run `gen.sh`? If it works, run `go test ./...` and check in the result.

**Comment by glacials** [comment]
Seems to have worked, thanks for reaching out and handling that!
```sh
./gen.sh
```
```
go: downloading modernc.org/ccgo/v3 v3.12.52
go: downloading modernc.org/libc v1.11.50
go: downloading modernc.org/cc/v3 v3.35.16
target: darwin/arm64
host config cmd: /opt/homebrew/bin/cpp-11
C front end 1/11: upstream/tree-sitter/lib/src/get_changed_ranges.c ... 69.927708ms
C front end 2/11: upstream/tree-sitter/lib/src/language.c ... 19.63025ms
C front end 3/11: upstream/tree-sitter/lib/src/lexer.c ... 26.322958ms
C front end 4/11: upstream/tree-sitter/lib/src/lib.c ... 104.239ms
C front end 5/11: upstream/tree-sitter/lib/src/node.c ... 28.328333ms
C front end 6/11: upstream/tree-sitter/lib/src/parser.c ... 38.373084ms
C front end 7/11: upstream/tree-sitter/lib/src/query.c ... 30.286792ms
C front end 8/11: upstream/tree-sitter/lib/src/stack.c ... 40.717625ms
C front end 9/11: upstream/tree-sitter/lib/src/subtree.c ... 24.226333ms
C front end 10/11: upstream/tree-sitter/lib/src/tree.c ... 31.998625ms
C front end 11/11: upstream/tree-sitter/lib/src/tree_cursor.c ... 19.391334ms
processing file scope declarations ... 33.461209ms
processing symbol table ... 767.333µs
processing struct/union types ... 88.555791ms
processing enum values ... 4.012708ms
processing #defines ... 1.946291ms
processing static local declarations ... 25.637125ms
Go back end 1/11: get_changed_ranges.c ... 21.659375ms
Go back end 2/11: language.c ... 5.248625ms
Go back end 3/11: lexer.c ... 9.463166ms
Go back end 4/11: lib.c ... 164.794625ms
Go back end 5/11: node.c ... 3.381ms
Go back end 6/11: parser.c ... 3.816208ms
Go back end 7/11: query.c ... 3.916417ms
Go back end 8/11: stack.c ... 3.758167ms
Go back end 9/11: subtree.c ... 3.683917ms
Go back end 10/11: tree.c ... 3.166333ms
Go back end 11/11: tree_cursor.c ... 3.274416ms
target: darwin/arm64
host config cmd: /opt/homebrew/bin/cpp-11
C front end 1/1: upstream/tree-sitter-json/src/parser.c ... 36.548166ms
processing file scope declarations ... 1.401041ms
processing symbol table ... 179µs
processing struct/union types ... 3.292834ms
processing enum values ... 240.208µs
processing #defines ... 841.791µs
processing static local declarations ... 349.208µs
Go back end 1/1: parser.c ... 10.305125ms
target: darwin/arm64
host config cmd: /opt/homebrew/bin/cpp-11
C front end 1/2: upstream/tree-sitter-python/src/parser.c ... 226.100416ms
C front end 2/2: internal/python/patch/scanner.c ... 13.706541ms
processing file scope declarations ... 3.369792ms
processing symbol table ... 144.458µs
processing struct/union types ... 49.310917ms
processing enum values ... 824.125µs
processing #defines ... 1.042125ms
processing static local declarations ... 2.166125ms
Go back end 1/2: parser.c ... 191.472042ms
Go back end 2/2: scanner.c ... 8.694208ms
```
```sh
go test ./...
```
```
ok  	github.com/yourbase/treesitter	0.116s
?   	github.com/yourbase/treesitter/internal/json	[no test files]
?   	github.com/yourbase/treesitter/internal/lang	[no test files]
?   	github.com/yourbase/treesitter/internal/lib	[no test files]
?   	github.com/yourbase/treesitter/internal/python	[no test files]
?   	github.com/yourbase/treesitter/json	[no test files]
?   	github.com/yourbase/treesitter/python	[no test files]
```

**Review by zombiezen — APPROVED** [review]
LGTM. Thanks @glacials!

**Pull request merged**
